# -*- coding: utf-8 -*-
"""encoder_keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uD0Wz05lBirXW6dXnlZYSArfu0MMKl4X
"""

from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

def build_lstm_encoder(window_size=50, latent_dim=32):
    """Encoder LSTM que genera embeddings de ventanas temporales"""
    inputs = keras.Input(shape=(window_size, 1))
    x = layers.LSTM(64, return_sequences=False)(inputs)
    outputs = layers.Dense(latent_dim, activation='linear')(x)
    return keras.Model(inputs, outputs, name='lstm_encoder')

def build_autoencoder(window_size=50, latent_dim=32):
    """Autoencoder completo — usamos solo el encoder para embeddings"""
    # Encoder
    inputs = keras.Input(shape=(window_size,))
    encoded = layers.Dense(128, activation='relu')(inputs)
    encoded = layers.Dense(64, activation='relu')(encoded)
    latent = layers.Dense(latent_dim, activation='linear', name='latent')(encoded)

    # Decoder
    decoded = layers.Dense(64, activation='relu')(latent)
    decoded = layers.Dense(128, activation='relu')(decoded)
    outputs = layers.Dense(window_size, activation='linear')(decoded)

    autoencoder = keras.Model(inputs, outputs, name='autoencoder')
    encoder = keras.Model(inputs, latent, name='encoder')

    autoencoder.compile(optimizer='adam', loss='mse')
    return autoencoder, encoder

def generate_embeddings(encoder, windows):
    """Genera embeddings para todas las ventanas"""
    if len(windows.shape) == 2:
        # Para el Autoencoder (entrada plana)
        return encoder.predict(windows, verbose=0)
    else:
        # Para el LSTM (entrada 3D)
        return encoder.predict(windows, verbose=0)