# -*- coding: utf-8 -*-
"""pipeline_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIaqHGFAnYMb5EJjAkMcHkAaMq6ZBke_
"""

# Install faiss-cpu if not already installed
!pip install faiss-cpu

import numpy as np
import faiss
from sklearn.preprocessing import StandardScaler

class TemporalRAGSystem:
    """
    Sistema RAG Temporal completo.
    Integra encoder, índice FAISS y generador híbrido.
    """
    def __init__(self, encoder, latent_dim=32, k=5):
        self.encoder = encoder
        self.latent_dim = latent_dim
        self.k = k
        self.index = faiss.IndexFlatL2(latent_dim)
        self.stored_windows = []
        self.stored_labels = []

    def build_memory(self, windows, labels=None):
        """Fase de indexación: construye la memoria histórica"""
        embeddings = self.encoder.predict(windows, verbose=0)
        embeddings = embeddings.astype('float32')
        faiss.normalize_L2(embeddings)
        self.index.add(embeddings)
        self.stored_windows = windows
        if labels is not None:
            self.stored_labels = labels
        print(f"Memoria construida: {self.index.ntotal} ventanas indexadas")

    def retrieve(self, query_window):
        """Recupera las k ventanas más similares a la consulta"""
        query_emb = self.encoder.predict(
            query_window.reshape(1, -1), verbose=0
        ).astype('float32')
        faiss.normalize_L2(query_emb)
        distances, indices = self.index.search(query_emb, self.k)
        return self.stored_windows[indices[0]], distances[0], indices[0]

    def anomaly_score_with_context(self, query_window, retrieved_windows):
        """
        Score de anomalía enriquecido con contexto histórico.
        Compara la ventana actual con las k recuperadas.
        """
        # Score base: distancia promedio a los k vecinos
        query_emb = self.encoder.predict(
            query_window.reshape(1, -1), verbose=0
        )
        retrieved_embs = self.encoder.predict(retrieved_windows, verbose=0)

        distances = np.mean(
            np.linalg.norm(retrieved_embs - query_emb, axis=1)
        )
        return distances

    def predict_with_context(self, query_window, retrieved_windows,
                              forecast_model):
        """
        Predicción enriquecida con contexto.
        El forecast_model recibe la ventana actual + media del contexto.
        """
        context_mean = retrieved_windows.mean(axis=0)
        enriched_input = np.concatenate([
            query_window, context_mean
        ]).reshape(1, -1)
        return forecast_model.predict(enriched_input, verbose=0)